//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidDesktop.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Appointment
    {
        public long ID { get; set; }
        public long TimeTableID { get; set; }
        public int ComponentTypeID { get; set; }
        public int PatientID { get; set; }
        public bool IsReceived { get; set; }
    
        public virtual ComponentType ComponentType { get; set; }
        public virtual Patient Patient { get; set; }
        public virtual TimeTable TimeTable { get; set; }
    }
}
