//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CovidDesktop.Base
{
    using System;
    using System.Collections.Generic;
    
    public partial class Questionnnare
    {
        public int ID { get; set; }
        public int PatientID { get; set; }
        public Nullable<bool> IsSickBefore { get; set; }
        public Nullable<bool> IsSomeWhat { get; set; }
    
        public virtual Patient Patient { get; set; }
    }
}
